### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [yih365/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - please embed the link to the website that your reader can download VSCode from
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - please make sure the last step covers this section from lab 1: use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
good job! feel free to comment below if you've any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by yih365** [comment]
Hi, my gradescope page for Lab Report 1 doesn't show a regrade button even after I click onto a specific assignment question. I was wondering if regrades are enabled yet.

**Comment by farnaf** [comment]
Hi there! We haven't released the grades yet. But everything looks good now, so I'll update your score to 1/1 - no need for a regrade request (:
